### PR TITLE
Update modulefiles and submodules to develop - late June 2024

### PR DESCRIPTION
**Pull request by CoryMartin-NOAA**
Update modulefile for Orion for Rocky9, include WCOSS modulefile (use at your own risk), and update submodules to the develop hashes.

### CODE REVIEW

**Review by ShunLiu-NOAA — DISMISSED** [review]

**Comment by JingCheng-NOAA** [comment]
The test of installation on Orion failed with following error message:
```
Building HDASApp on orion
Lmod has detected the following error: These module(s) or extension(s) exist but cannot be loaded
as requested: "curl/8.4.0", "stack-intel/2021.9.0", "openblas/0.3.24", "krb5/1.20.1",
"cmake/3.23.1", "openjpeg/2.3.1", "netcdf-fortran/4.6.1", "nco/5.0.6", "boost/1.83.0"
   Try: "module spider curl/8.4.0 stack-intel/2021.9.0 openblas/0.3.24 krb5/1.20.1 cmake/3.23.1
openjpeg/2.3.1 netcdf-fortran/4.6.1 nco/5.0.6 boost/1.83.0" to see how to load the module(s).
```

**Comment by CoryMartin-NOAA** [comment]
Orion is still currently all screwed up with the Rocky9 transition, so I wouldn't expect anything to build there at the moment.

**Comment by JingCheng-NOAA** [comment]
> Orion is still currently all screwed up with the Rocky9 transition, so I wouldn't expect anything to build there at the moment.

Understand. The installation on Hera works fine. I will approve this PR for now.

**Review by JingCheng-NOAA — DISMISSED** [review]

**Review by XuLu-NOAA — DISMISSED** [review]

**Review by JingCheng-NOAA — APPROVED** [review]

**Review by XuLu-NOAA — APPROVED** [review]

**Review by ShunLiu-NOAA — APPROVED** [review]

**Comment by ShunLiu-NOAA** [comment]
The changes looks good to me and Jing and Xu have approved the PR. The PR will be merged to develop this if no objections are received today.

**Pull request merged**
